from pathlib import Path
root = Path(__file__).resolve().parents[1]
checks=[]
def read(rel): return (root/rel).read_text(encoding='utf-8')
def ok(label, cond):
    if not cond: raise SystemExit(f'[FAIL] {label}')
    checks.append(label); print(f'[PASS] {label}')
network=read('core/network/build.gradle.kts')
bootstrap=read('feature/bootstrap/build.gradle.kts')
database=read('core/database/build.gradle.kts')
prefs=read('core/preferences/build.gradle.kts')
design=read('core/designsystem/build.gradle.kts')
interceptor=read('core/network/src/main/java/app/voicecloud/core/network/AuthTokenInterceptor.kt')
repo=read('feature/bootstrap/src/main/java/app/voicecloud/feature/bootstrap/BootstrapRepository.kt')
java_env=read('scripts/VC-ANDROID-JAVA-ENV.cmd')
accept=read('scripts/VC-ANDROID-PH01-R05-ACCEPTANCE.cmd')
ok('Bootstrap repository consumes Retrofit Response through network public ABI', 'response.body()' in repo and 'response.isSuccessful' in repo)
ok('Retrofit core exported from core:network public ABI', 'api(libs.retrofit.core)' in network)
ok('core:model exported from core:network public ABI', 'api(project(":core:model"))' in network)
ok('core:security exported from core:network public ABI', 'api(project(":core:security"))' in network)
ok('Moshi exported from core:network public ABI', 'api(libs.moshi.kotlin)' in network)
ok('OkHttp interceptor is internal implementation detail', 'internal class AuthTokenInterceptor' in interceptor)
ok('Room runtime exported for VoiceCloudDatabase public superclass', 'api(libs.androidx.room.runtime)' in database)
ok('Database Flow authority exported for public DAO ABI', 'api(libs.kotlinx.coroutines.android)' in database)
ok('Preferences Flow authority exported for public preference ABI', 'api(libs.kotlinx.coroutines.android)' in prefs)
ok('Compose UI exported for design-system public Color/Modifier/Dp ABI', 'api(libs.androidx.compose.ui)' in design)
ok('Bootstrap exports public model ABI', 'api(project(":core:model"))' in bootstrap)
ok('Bootstrap exports public network ABI', 'api(project(":core:network"))' in bootstrap)
ok('Bootstrap exports public logging ABI', 'api(project(":core:logging"))' in bootstrap)
ok('Windows Java resolver clears invalid JAVA_HOME', 'set "JAVA_HOME="' in java_env)
ok('Windows Java resolver auto-detects Android Studio JBR', r'%ProgramFiles%\Android\Android Studio\jbr' in java_env)
ok('R05 acceptance resolves Java before wrapper bootstrap', 'VC-ANDROID-JAVA-ENV.cmd' in accept and accept.index('VC-ANDROID-JAVA-ENV.cmd') < accept.index('gradle\\wrapper\\gradle-wrapper.jar'))
print(f'VC-ANDROID-PH01-R05 module ABI/runtime regression: {len(checks)}/{len(checks)} PASS')
