from pathlib import Path
root=Path(__file__).resolve().parents[1]
checks=[]
def read(rel): return (root/rel).read_text(encoding="utf-8")
def ok(label, cond):
    if not cond: raise SystemExit(f"[FAIL] {label}")
    checks.append(label); print(f"[PASS] {label}")
resolver=read("app/src/main/java/app/voicecloud/android/network/ApiEndpointResolver.kt")
foundation=read("app/src/main/java/app/voicecloud/android/di/FoundationModule.kt")
appgradle=read("app/build.gradle.kts")
mainsec=read("app/src/main/res/xml/network_security_config.xml")
dbgsec=read("app/src/debug/res/xml/network_security_config.xml")
stgsec=read("app/src/staging/res/xml/network_security_config.xml")
helper=read("scripts/VC-ANDROID-LOCAL-DEVICE-BACKEND.cmd")
accept=read("scripts/VC-ANDROID-PH01-R06-ACCEPTANCE.cmd")
ok("default debug build still declares emulator host alias", "http://10.0.2.2:3000/api/v1/" in appgradle)
ok("physical device default is adb-reverse localhost", "http://127.0.0.1:3000/api/v1/" in resolver)
ok("emulator detection preserves 10.0.2.2", "if (emulator) EmulatorDebugBaseUrl else PhysicalDeviceDebugBaseUrl" in resolver)
ok("explicit VC_API_BASE_URL override remains authoritative", "if (configuredBaseUrl != EmulatorDebugBaseUrl) return configuredBaseUrl" in resolver)
ok("release/staging are never rewritten by debug resolver", "if (!debug) return configuredBaseUrl" in resolver)
ok("Retrofit receives runtime-resolved endpoint", "ApiEndpointResolver.resolve(BuildConfig.API_BASE_URL, BuildConfig.DEBUG)" in foundation)
ok("main network security denies cleartext", 'cleartextTrafficPermitted="false"' in mainsec and 'cleartextTrafficPermitted="true"' not in mainsec)
ok("staging network security denies cleartext", 'cleartextTrafficPermitted="true"' not in stgsec)
ok("debug permits local/LAN cleartext development while release stays closed", 'cleartextTrafficPermitted="true"' in dbgsec)
ok("device helper uses SDK-owned adb", r'%ANDROID_HOME%\platform-tools\adb.exe' in helper)
ok("device helper creates port 3000 reverse", "reverse tcp:3000 tcp:3000" in helper)
ok("device helper verifies reverse mapping", "reverse --list" in helper)
ok("R06 acceptance prepares device tunnel after SDK resolution", "VC-ANDROID-LOCAL-DEVICE-BACKEND.cmd" in accept and accept.index("VC-ANDROID-SDK-ENV.cmd") < accept.index("VC-ANDROID-LOCAL-DEVICE-BACKEND.cmd"))
ok("R06 acceptance retains compile gates", all(x in accept for x in [":app:compileDebugKotlin",":app:compileStagingKotlin",":app:compileReleaseKotlin"]))
print(f"VC-ANDROID-PH01-R06 real-device network regression: {len(checks)}/{len(checks)} PASS")
