from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def text(rel): return (ROOT/rel).read_text(encoding='utf-8')
def ck(name, cond):
    if not cond: raise SystemExit(f'[FAIL] {name}')
    checks.append(name); print(f'[PASS] {name}')
vm=text('feature/live/src/main/java/app/voicecloud/feature/live/ui/LiveRoomViewModel.kt')
rtc=text('feature/live/src/main/java/app/voicecloud/feature/live/rtc/RtcAudioEngine.kt')
screens=text('feature/live/src/main/java/app/voicecloud/feature/live/ui/LiveRoomScreens.kt')
ck('join and rejoin jobs are independently cancellable', 'joinJob?.cancel()' in vm and 'rejoinJob?.cancel()' in vm)
leave_block=vm[vm.index('fun leave()'):vm.index('fun toggleSave()')]
ck('leave invalidates session before cleanup', leave_block.index('val invalidatedGeneration = invalidateSession()') < leave_block.index('runCatching { repository.leave(roomId) }'))
ck('leave clears UI membership synchronously', vm.index('inRoom = false', vm.index('fun leave()')) < vm.index('viewModelScope.launch', vm.index('fun leave()')))
ck('stale session guard uses generation and room id', 'sessionGeneration == generation && activeRoomId == roomId' in vm)
ck('join checks stale session after backend token', vm.index('val join = repository.join(roomId)') < vm.index('ensureCurrentSession(generation, roomId)', vm.index('val join = repository.join(roomId)')))
ck('join checks stale session after LiveKit connect', vm.index('rtcEngine.connect(join.serverUrl!!.trim(), join.token)') < vm.index('ensureCurrentSession(generation, roomId)', vm.index('rtcEngine.connect(join.serverUrl!!.trim(), join.token)')))
ck('rejoin checks stale session before API', vm.index('ensureCurrentSession(generation, roomId)', vm.index('private fun scheduleRejoin()')) < vm.index('repository.rejoin(roomId, prior.token)'))
ck('rejoin checks stale session after LiveKit connect', vm.index('rtcEngine.connect(refreshed.serverUrl!!.trim(), refreshed.token)') < vm.index('ensureCurrentSession(generation, roomId)', vm.index('rtcEngine.connect(refreshed.serverUrl!!.trim(), refreshed.token)')))
ck('cancelled coroutines are rethrown', vm.count('catch (cancelled: CancellationException)') >= 3 and vm.count('throw cancelled') >= 3)
ck('extras are session gated', vm.count('isCurrentSession(generation, room.id)') >= 3)
ck('chat refresh is session gated', 'while (isCurrentSession(generation, roomId)' in vm)
ck('participant refresh is session gated', 'participantRefreshJob?.cancel()' in vm and 'isCurrentSession(generation, roomId)' in vm)
ck('server-ended room cancels outstanding jobs', 'private fun endFromServer()' in vm and 'cancelSessionJobs()' in vm)
ck('ViewModel clear cancels outstanding jobs', 'override fun onCleared()' in vm and 'invalidateSession()' in vm)
ck('engine connection generation is atomic', 'AtomicLong' in rtc)
ck('engine ownership mutation is synchronized', rtc.count('synchronized(ownershipLock)') >= 3)
ck('new engine connect removes prior owner atomically', 'beginConnectionOperation()' in rtc and 'takeOwnedConnectionLocked()' in rtc)
ck('disconnect invalidates prior engine operation', 'generation.incrementAndGet()' in rtc and 'override fun disconnect()' in rtc)
ck('stale engine event cannot update state', 'if (generation.get() != operation) return@collect' in rtc)
ck('stale engine connect is cancelled', 'Audio connection superseded' in rtc)
ck('engine cleans only matching owned references', 'if (room === active) room = null' in rtc and 'if (eventsJob === eventJob) eventsJob = null' in rtc)
ck('room screen leaves on composition disposal', 'DisposableEffect(roomId) { onDispose { onLeave() } }' in screens)
ck('background does not force room leave', 'Do not leave the room when the app backgrounds' in vm)
ck('foreground retries disconnected audio', 'if (mutableState.value.rtcState is RtcAudioState.Disconnected) scheduleRejoin()' in vm)
print(f'VC-ANDROID-PH05-R01 lifecycle race regression: {len(checks)}/{len(checks)} PASS')
