from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
checks=[]
def t(rel): return (ROOT/rel).read_text(encoding='utf-8')
def ck(name, cond):
    if not cond: raise SystemExit(f'[FAIL] {name}')
    checks.append(name); print(f'[PASS] {name}')

settings=t('settings.gradle.kts'); app=t('app/build.gradle.kts'); versions=t('gradle/libs.versions.toml')
api=t('feature/live/src/main/java/app/voicecloud/feature/live/data/LiveRoomApi.kt')
repo=t('feature/live/src/main/java/app/voicecloud/feature/live/data/LiveRoomRepository.kt')
vm=t('feature/live/src/main/java/app/voicecloud/feature/live/ui/LiveRoomViewModel.kt')
rtc=t('feature/live/src/main/java/app/voicecloud/feature/live/rtc/RtcAudioEngine.kt')
realtime=t('feature/live/src/main/java/app/voicecloud/feature/live/data/LiveRoomRealtimeMonitor.kt')
screens=t('feature/live/src/main/java/app/voicecloud/feature/live/ui/LiveRoomScreens.kt')
models=t('feature/live/src/main/java/app/voicecloud/feature/live/model/LiveRoomModels.kt')
policy=t('feature/live/src/main/java/app/voicecloud/feature/live/model/RoomAccessPolicy.kt')
nav=t('app/src/main/java/app/voicecloud/android/navigation/VoiceCloudNavHost.kt')
manifest=t('app/src/main/AndroidManifest.xml'); styles=t('app/src/main/res/values/styles.xml'); activity=t('app/src/main/java/app/voicecloud/android/MainActivity.kt')
discovery=t('feature/discovery/src/main/java/app/voicecloud/feature/discovery/ui/DiscoveryScreens.kt')
brand=t('branding/voicecloud-brand.properties'); design_build=t('core/designsystem/build.gradle.kts')
colors=t('core/designsystem/src/main/java/app/voicecloud/core/designsystem/theme/VoiceCloudColors.kt')
notif=t('app/src/main/java/app/voicecloud/android/notifications/VoiceCloudFirebaseMessagingService.kt')

ck('PH05 live module registered', 'include(":feature:live")' in settings)
ck('app consumes PH05 live module', 'implementation(project(":feature:live"))' in app)
ck('PH05 or later version marker present', 'versionName = "1.0.0-ph0' in app and 'versionName = "1.0.0-ph01"' not in app)
ck('LiveKit Android 2.28.0 pinned', 'livekitAndroid = "2.28.0"' in versions and 'implementation(libs.livekit.android)' in t('feature/live/build.gradle.kts'))
for ep in ['rooms/{roomId}', 'rtc/rooms/join', 'rtc/rooms/rejoin', 'rtc/rooms/leave', 'rtc/rooms/{roomId}/participants',
           'rtc/rooms/{roomId}/raise-hand', 'rtc/rooms/{roomId}/cancel-raise-hand', 'chat/conversations',
           'chat/conversations/{conversationId}/messages', 'chat/messages/{messageId}/reactions', 'rooms/saved/{roomId}/status',
           'rooms/saved/{roomId}', 'room-activity/{roomId}/join', 'room-activity/{roomId}/leave', 'gifts/catalog', 'gifts/send']:
    ck(f'PH05 endpoint {ep} retained', ep in api)
ck('join is listener-only', 'role: String = "listener"' in models)
ck('white-label device identity used for RTC join', 'VoiceCloudBrand.slug' in repo and '-android' in repo)
ck('activity join follows backend RTC join', 'api.activityJoin' in repo)
ck('activity leave follows backend RTC leave', 'api.activityLeave' in repo)
ck('participants are deduplicated', 'participants.distinctBy { it.userId }' in repo)
ck('room chat messages are deduplicated', 'messages.distinctBy { it.id }' in repo)
ck('gift catalog is deduplicated', 'distinctBy { it.id }' in repo and 'api.giftCatalog()' in repo)
ck('gift sends use idempotency operation key', 'operationKey = UUID.randomUUID().toString()' in repo)
for state in ['isLocked', 'isInviteOnly', 'isTicketRequired', 'isPremium', 'isSubscriberOnly', 'isVerifiedOnly', 'clubId']:
    ck(f'room access presentation covers {state}', state in policy)
ck('join failure maps access states safely', all(x in repo for x in ['"ticket"', '"subscription"', '"verification"', '"club"', '"invite"', '"locked"', '"full"', '"offline"']))
ck('room access errors are sanitized', 'sanitizeMessage' in repo and 'takeIf { it.length in 4..220 }' in repo)
ck('room preview route exists', 'const val RoomPreview = "rooms/{roomId}/preview"' in nav)
ck('live room route exists', 'const val RoomExperience = "rooms/{roomId}/live"' in nav)
ck('room preview opens listener experience', 'onJoin = { open(VoiceCloudRoutes.roomExperience(roomId)) }' in nav)
ck('discovery routes rooms through preview', 'roomPreview(it)' in nav)
ck('live screen disposes by leaving room', 'DisposableEffect(roomId) { onDispose { onLeave() } }' in screens)
ck('live screen tracks app foreground/background', 'Lifecycle.Event.ON_START' in screens and 'Lifecycle.Event.ON_STOP' in screens)
ck('listener engine auto subscribes', 'autoSubscribe = true' in rtc)
ck('listener engine never captures microphone', 'audio = false' in rtc)
ck('listener engine never captures camera', 'video = false' in rtc)
ck('PH05 listener UI does not request microphone permission', 'RequestPermission' not in screens and 'RECORD_AUDIO' not in screens)
ck('engine has connection generation ownership', 'AtomicLong' in rtc and 'beginConnectionOperation()' in rtc and 'ownershipLock' in rtc)
ck('engine stale connections fail by cancellation', 'CancellationException("Audio connection superseded")' in rtc)
ck('engine cleanup only clears owned room', 'if (room === active) room = null' in rtc)
ck('ViewModel tracks join job', 'private var joinJob: Job?' in vm)
ck('ViewModel tracks rejoin job', 'private var rejoinJob: Job?' in vm)
ck('ViewModel tracks extras job', 'private var extrasJob: Job?' in vm)
ck('ViewModel tracks participant refresh job', 'private var participantRefreshJob: Job?' in vm)
ck('ViewModel tracks message refresh job', 'private var messageRefreshJob: Job?' in vm)
ck('ViewModel uses session generation', 'private var sessionGeneration = 0L' in vm)
ck('leave invalidates room session before async cleanup', 'val invalidatedGeneration = invalidateSession()' in vm and 'cancelSessionJobs()' in vm)
ck('leave clears in-room state immediately', 'inRoom = false' in vm and 'joinResult = null' in vm)
ck('stale join results are guarded', vm.count('ensureCurrentSession(generation, roomId)') >= 6)
ck('rejoin is generation guarded', 'val generation = sessionGeneration' in vm and 'repository.rejoin(roomId, prior.token)' in vm)
ck('cancelled join is not converted into access error', 'catch (cancelled: CancellationException)' in vm and 'throw cancelled' in vm)
ck('server end invalidates and cancels room jobs', 'invalidateSession()' in vm and 'private fun endFromServer()' in vm)
ck('ViewModel teardown invalidates and cancels session', 'override fun onCleared()' in vm and 'cancelSessionJobs()' in vm)
ck('five-second room chat refresh retained', 'delay(5_000)' in vm)
ck('room extras cannot update stale session', 'isCurrentSession(generation, room.id)' in vm)
ck('participant refresh cannot update stale session', 'isCurrentSession(generation, roomId)' in vm)
for event in ['participant_joined','participant_left','participant_reconnected','presence_updated','reaction:broadcast','emoji_reaction_received',
              'hand_approved','hand_rejected','speaker_invitation_sent','speaker_invitation_rejected','speaker_promoted','speaker_demoted',
              'speaker_removed','speaker_muted','speaker_unmuted','stage_updated','rtc_token_refreshed','rtc_session_ended',
              'gift.sent','gift.received','gift.animation','room.paused','room.resumed','room.ended']:
    ck(f'PH05 realtime event {event} retained', event in realtime)
ck('authenticated realtime presence join retained', 'presence:join' in realtime)
ck('authenticated realtime presence reconnect retained', 'presence:reconnect' in realtime)
ck('authenticated realtime presence leave retained', 'presence:leave' in realtime)
ck('reaction send event retained', 'reaction:send' in realtime)
ck('speaker invitation acceptance retained', 'stage:accept_invitation' in realtime)
ck('speaker invitation rejection retained', 'stage:reject_invitation' in realtime)
ck('participant lazy list keys are collision-safe', 'live-person:${participant.userId}:$index' in screens)
ck('chat lazy list keys are collision-safe', 'live-chat:${message.id}:$index' in screens)
ck('gift lazy list keys are collision-safe', 'live-gift:${gift.id}:$index' in screens)

for icon in ['home','explore','search','friends','profile']:
    ck(f'tab vector icon {icon} exists', (ROOT/f'core/designsystem/src/main/res/drawable/vc_nav_{icon}.xml').exists())
    ck(f'tab {icon} uses real vector resource', f'R.drawable.vc_nav_{icon}' in discovery)
ck('tab bar renders professional vector Icon painters', 'vc_nav_home_selected' in discovery and 'painterResource(if (isSelected)' in discovery and '●' not in discovery and '○' not in discovery)
ck('splashscreen dependency pinned', 'coreSplashscreen = "1.2.0"' in versions and 'implementation(libs.androidx.core.splashscreen)' in app)
ck('MainActivity installs Android splash screen', 'installSplashScreen()' in activity)
ck('starting theme uses SplashScreen API', 'parent="Theme.SplashScreen"' in styles)
ck('starting theme uses replaceable brand splash', '@drawable/vc_brand_splash' in styles)
ck('temporary splash asset exists in central branding tree', (ROOT/'branding/res/drawable/vc_brand_splash.xml').exists())
ck('app icon foreground exists in central branding tree', (ROOT/'branding/res/drawable/vc_brand_app_icon_foreground.xml').exists())
ck('design system consumes centralized branding resource tree', 'branding/res' in design_build)
for key in ['brand.name','brand.slug','brand.applicationId','brand.legalName','brand.tagline','consumer.sapphire','consumer.primaryGradientStart','creator.primary','common.error','radius.medium','motion.standardMs']:
    ck(f'white-label authority contains {key}', f'{key}=' in brand)
ck('applicationId comes from white-label authority', 'applicationId = brand("brand.applicationId")' in app)
ck('app display name comes from white-label authority', 'resValue("string", "vc_brand_app_name", brand("brand.name"))' in app and '@string/vc_brand_app_name' in manifest)
ck('launcher background comes from white-label authority', 'resValue("color", "vc_brand_launcher_background", brand("consumer.sapphire"))' in app)
ck('notification channel uses white-label brand slug', 'VoiceCloudBrand.slug' in notif and '_general' in notif)
ck('notification title/body use white-label brand name', notif.count('VoiceCloudBrand.name') >= 2)
ck('consumer colors resolve through generated branding BuildConfig', 'VoiceCloudBrand.color(BuildConfig.CONSUMER_SAPPHIRE)' in colors)
ck('PH05 listener remains receive-only as host publishing evolves', 'audio = false' in rtc and 'video = false' in rtc and 'setMicrophoneEnabled' not in (vm+screens))
ck('PH05 live module remains isolated from host management', 'feature:hosting' not in t('feature/live/build.gradle.kts'))

print(f'VC-ANDROID-PH05-R01 source authority: {len(checks)}/{len(checks)} PASS')
