from pathlib import Path
R=Path(__file__).resolve().parents[1]; c=[]
def t(x): return (R/x).read_text()
def ck(n,v):
 if not v: raise SystemExit('[FAIL] '+n)
 c.append(n); print('[PASS] '+n)
nav=t('app/src/main/java/app/voicecloud/android/navigation/VoiceCloudNavHost.kt')
disc=t('feature/discovery/src/main/java/app/voicecloud/feature/discovery/ui/DiscoveryScreens.kt')
metrics=t('core/designsystem/src/main/java/app/voicecloud/core/designsystem/theme/VoiceCloudPageMetrics.kt')
top=t('core/designsystem/src/main/java/app/voicecloud/core/designsystem/component/VoiceCloudPageTopBar.kt')
ck('Telegram-style directional slide used', 'slideInHorizontally' in nav and 'slideOutHorizontally' in nav)
ck('tab fade is restrained', 'fadeIn' in nav and 'fadeOut' in nav)
ck('tab motion is short', 'tween(190)' in nav and 'fullWidth / 5' in nav)
ck('motion applies only main consumer tabs', 'consumerTabs = listOf' in nav and 'from < 0 || to < 0' in nav)
for r in ['Home','Explore','Search','Friends','MyProfile']: ck(f'main tab {r} in motion order', f'VoiceCloudRoutes.{r}' in nav)
for icon in ['home','explore','search','friends','profile']:
 ck(f'{icon} outline vector exists',(R/f'core/designsystem/src/main/res/drawable/vc_nav_{icon}.xml').exists())
 ck(f'{icon} selected vector exists',(R/f'core/designsystem/src/main/res/drawable/vc_nav_{icon}_selected.xml').exists())
ck('selected icon resource is state aware','painterResource(if (isSelected) item.selectedIcon else item.outlineIcon)' in disc)
ck('adaptive page metrics central','object VoiceCloudPageMetrics' in metrics)
for bp in ['widthDp < 360.dp','widthDp < 600.dp']: ck('adaptive breakpoint '+bp,bp in metrics)
for field in ['horizontalPadding','contentTopSpacing','contentBottomSpacing','topBarMinHeight','bottomBarHeight','bottomIconSize','sectionSpacing']: ck('metric '+field,field in metrics)
ck('shared header consumes adaptive height','.heightIn(min = metrics.topBarMinHeight)' in top)
ck('shared header consumes adaptive horizontal padding','metrics.horizontalPadding' in top)
ck('tab footer consumes adaptive height','Modifier.height(metrics.bottomBarHeight)' in disc)
ck('tab icons consume adaptive size','Modifier.size(metrics.bottomIconSize)' in disc)
ck('main header consumes adaptive spacing','vertical = metrics.contentTopSpacing' in disc)
ck('home shortcut grid avoids four cramped labels','HomeShortcut("Host Studio"' in disc and disc.count('Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp))') >= 2)
print(f'VC-ANDROID-PH06-R01 UI motion/spacing regression: {len(c)}/{len(c)} PASS')
