from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def t(rel): return (ROOT/rel).read_text(encoding='utf-8')
def ck(name, cond):
    if not cond: raise SystemExit(f'[FAIL] {name}')
    checks.append(name); print(f'[PASS] {name}')
settings=t('settings.gradle.kts'); app=t('app/build.gradle.kts'); manifest=t('app/src/main/AndroidManifest.xml')
api=t('feature/hosting/src/main/java/app/voicecloud/feature/hosting/data/HostingApi.kt')
repo=t('feature/hosting/src/main/java/app/voicecloud/feature/hosting/data/HostingRepository.kt')
vm=t('feature/hosting/src/main/java/app/voicecloud/feature/hosting/ui/HostingViewModel.kt')
ui=t('feature/hosting/src/main/java/app/voicecloud/feature/hosting/ui/HostingScreens.kt')
models=t('feature/hosting/src/main/java/app/voicecloud/feature/hosting/model/HostingModels.kt')
nav=t('app/src/main/java/app/voicecloud/android/navigation/VoiceCloudNavHost.kt')
rtc=t('feature/live/src/main/java/app/voicecloud/feature/live/rtc/RtcAudioEngine.kt')

a=[('hosting module registered','include(":feature:hosting")' in settings),('app consumes hosting','implementation(project(":feature:hosting"))' in app),('PH06 version','versionName = "1.0.0-ph06"' in app),('record audio permission','android.permission.RECORD_AUDIO' in manifest)]
for n,c in a: ck(n,c)
for ep in ['hosts/profile','hosts/eligibility','rooms/mine','rooms/{roomId}','rooms/{roomId}/start','rooms/{roomId}/pause','rooms/{roomId}/resume','rooms/{roomId}/end','scheduled-rooms','scheduled-rooms/{scheduleId}','rtc/rooms/join','rtc/rooms/leave','rtc/rooms/{roomId}/stage','rtc/rooms/{roomId}/approve-speaker','rtc/rooms/{roomId}/reject-speaker','rtc/rooms/{roomId}/invite-speaker','rtc/rooms/{roomId}/remove-speaker','rtc/rooms/{roomId}/mute-user','rtc/rooms/{roomId}/lock-seat','polls/rooms/{roomId}','polls/{pollId}/start','polls/{pollId}/stop','quizzes/rooms/{roomId}/active','quizzes/{quizId}/start','quizzes/{quizId}/next-round','quizzes/{quizId}/stop']:
    ck(f'backend endpoint {ep}', ep in api)
ck('host access checked before management', 'repository.hostAccess()' in vm and 'profile?.status.equals("APPROVED", true)' in vm)
ck('host eligibility exact applications flag', 'applicationsEnabled' in models and 'HostEligibilityRequirements' in models)
ck('scheduled visibility normalized uppercase', 'visibility = visibility.uppercase()' in repo and '"PRIVATE" else "PUBLIC"' in ui)
ck('scheduled time normalized as OffsetDateTime', 'OffsetDateTime.parse(scheduledStartTime).toString()' in repo and '.toOffsetDateTime()' in ui)
ck('schedule device timezone retained', 'ZoneId.systemDefault()' in ui and 'timeZone = zone.id' in ui)
ck('schedule uses date picker', 'DatePickerDialog' in ui)
ck('schedule uses 12-hour display', 'hh:mm a' in ui)
ck('future schedule required', 'Choose a future date and time.' in ui)
ck('ticket access on room editor', 'isTicketRequired = ticketed' in ui and 'ticketPriceAmount' in ui)
ck('room access controls present', all(x in ui for x in ['Private room','Invite only','Subscribers only','Verified listeners only']))
for route in ['HostStudio','HostRoomCreate','HostRoomManage','HostRoomSettings','HostLiveConsole','HostScheduleCreate','HostScheduleEdit','HostInteractive']:
    ck(f'route {route}', f'const val {route}' in nav and f'composable(VoiceCloudRoutes.{route})' in nav)
ck('static room create cannot collide with dynamic manage', 'host/rooms/{roomId}/manage' in nav)
ck('static schedule create cannot collide with dynamic edit', 'host/schedules/{scheduleId}/edit' in nav)
ck('home exposes host studio', 'onHostStudio' in nav and 'Host Studio' in t('feature/discovery/src/main/java/app/voicecloud/feature/discovery/ui/DiscoveryScreens.kt'))
ck('guest host entry upgrades first', 'viewer?.isGuest == true' in nav and 'VoiceCloudRoutes.GuestUpgrade' in nav)
ck('RTC host joins with host role', 'role: String = "host"' in models)
ck('listener connection remains receive only', 'ConnectOptions(autoSubscribe = true, audio = false, video = false)' in rtc)
ck('microphone publishing explicit', 'setMicrophoneEnabled(enabled: Boolean)' in rtc and 'localParticipant.setMicrophoneEnabled(enabled)' in rtc)
ck('microphone resets on new connection', 'mutableMicrophoneEnabled.value = false' in rtc)
ck('host UI permission gated', 'ActivityResultContracts.RequestPermission()' in ui and 'Manifest.permission.RECORD_AUDIO' in ui)
ck('listener UI does not request mic', 'RECORD_AUDIO' not in t('feature/live/src/main/java/app/voicecloud/feature/live/ui/LiveRoomScreens.kt'))
ck('host teardown disables mic', 'rtcEngine.setMicrophoneEnabled(false)' in vm and 'override fun onCleared()' in vm)
ck('host teardown disconnects RTC', 'rtcEngine.disconnect()' in vm and 'leaveHostConsole' in vm)
ck('stage refresh bounded', 'delay(3_000)' in vm and 'stageRefreshJob' in vm)
ck('stage lists deduplicated', 'handQueue.filter' in repo and 'speakers.filter' in repo and 'participants.filter' in repo)
for action in ['approve(','reject(','inviteSpeaker(','removeSpeaker(','muteSpeaker(','lockSeat(']: ck(f'stage action {action}', action in vm)
ck('participant invitations use authenticated realtime', 'RealtimeConnectionState.Authenticated' in repo and 'invite_participant' in repo)
ck('participant invitations use people search', '@GET("search")' in api and 'searchInviteCandidates' in vm and 'Search people' in ui)
ck('invite candidates exclude self guests privileged', 'it.id != selfId' in repo and '!it.isGuest' in repo and 'setOf("USER", "CREATOR")' in repo)
ck('poll requires at least two options in UI', 'parsedPollOptions.size >= 2' in ui)
ck('poll duration minimum enforced repository', 'coerceAtLeast(10)' in repo)
ck('quiz correct option validated', 'correctIndex in opts.indices' in ui)
ck('quiz question backend minimum defaults', 'durationSeconds: Int = 30' in models and 'points: Int = 100' in models)
ck('Host ViewModel cancellation generation retained', 'AtomicLong' in vm and 'sessionGeneration.incrementAndGet()' in vm)
ck('host connect stale guard retained', vm.count('isCurrent(generation, roomId)') >= 2)
ck('cancelled host join rethrown', 'catch (cancelled: CancellationException)' in vm and 'throw cancelled' in vm)
ck('PH07 economy not pulled into hosting module', 'wallet' not in api.lower() and 'payout' not in api.lower())
print(f'VC-ANDROID-PH06-R01 source authority: {len(checks)}/{len(checks)} PASS')
