from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def t(p): return (ROOT/p).read_text(encoding='utf-8')
def check(name, cond):
    if not cond: raise SystemExit(f'[FAIL] {name}')
    print(f'[PASS] {name}')

nav=t('app/src/main/java/app/voicecloud/android/navigation/VoiceCloudNavHost.kt')
dui=t('feature/discovery/src/main/java/app/voicecloud/feature/discovery/ui/DiscoveryScreens.kt')
dapi=t('feature/discovery/src/main/java/app/voicecloud/feature/discovery/data/DiscoveryApi.kt')
drepo=t('feature/discovery/src/main/java/app/voicecloud/feature/discovery/data/DiscoveryRepository.kt')
live=t('feature/live/src/main/java/app/voicecloud/feature/live/ui/LiveRoomScreens.kt')
eui=t('feature/economy/src/main/java/app/voicecloud/feature/economy/ui/EconomyScreens.kt')
papi=t('feature/profile/src/main/java/app/voicecloud/feature/profile/data/ProfileApi.kt')
prepo=t('feature/profile/src/main/java/app/voicecloud/feature/profile/data/ProfileRepository.kt')
pui=t('feature/profile/src/main/java/app/voicecloud/feature/profile/ui/ProfileScreens.kt')
billing=t('feature/economy/src/main/java/app/voicecloud/feature/economy/billing/PlayBillingCoordinator.kt')
evm=t('feature/economy/src/main/java/app/voicecloud/feature/economy/ui/EconomyViewModel.kt')
egradle=t('feature/economy/build.gradle.kts')

check('Search when expression has exhaustive fallback', '"Communities" -> itemsIndexed' in dui and 'else -> Unit' in dui)
check('Discovery lazy row items import present', 'import androidx.compose.foundation.lazy.items' in dui and 'import androidx.compose.foundation.lazy.itemsIndexed' in dui)
check('Friends raw response parsing uses Any consistently', ': Any' in dapi and 'itemMaps(' in drepo and 'unwrap(' in drepo)
check('Profile PUT annotations imported', 'import retrofit2.http.PUT' in papi and '@PUT("users/avatar")' in papi and '@PUT("users/cover")' in papi)
check('Profile media lambdas are suspend-aware', 'val primary: suspend () -> Any' in prepo and 'val fallback: suspend () -> Any' in prepo)
check('Profile blank checks avoid callable-reference ambiguity in UI', 'takeIf { it.isNotBlank() }' in pui)
check('Economy uses stable shared page top bar instead of direct experimental TopAppBar', 'VoiceCloudPageTopBar' in eui and 'TopAppBar(' not in eui)
check('Economy generic maps have stable nullable helpers', 'private fun Any?.isDisplayScalar()' in eui and 'private fun Map<String, Any?>.stableId()' in eui)
check('Live room Material3 bottom sheets are opted in', '@OptIn(ExperimentalMaterial3Api::class)' in live and 'ModalBottomSheet' in live)
check('Live room painter resources imported for floating icons', 'import androidx.compose.ui.res.painterResource' in live and 'vc_icon_emoji' in live and 'vc_icon_gift' in live)
check('Live-room leave is not double-invoked from close handler', 'val closeRoom: () -> Unit = { onBack() }' in live and 'DisposableEffect(roomId) { onDispose { onLeave() } }' in live)
check('Navigation call sites match new discovery callbacks', 'onLoadDefaults = {' in nav and 'onEconomySection = {' in nav and 'onCancel = vm::cancelFriendRequest' in nav)
check('Help detail route URI decoding is present', 'VoiceCloudRoutes.HelpPage' in nav and 'Uri.decode' in nav)
check('Secondary transitions retain no-op only for same route', 'if (fromRoute == toRoute) return EnterTransition.None' in nav)
check('Economy library BuildConfig generation is enabled', 'buildConfig = true' in egradle and 'buildConfigField("String", "VOICECLOUD_PAYMENT_MODE"' in egradle)
check('Billing 9 ProductDetails callback uses QueryProductDetailsResult list', 'queryResult.productDetailsList.firstOrNull()' in billing)
check('Billing flow uses ProductDetailsParams and optional offer token', 'BillingFlowParams.ProductDetailsParams.newBuilder()' in billing and 'setOfferToken(lookup.offerToken)' in billing)
check('Google purchase callback handles nullable purchases safely', 'purchases: List<Purchase>?' in billing and 'purchases.orEmpty()' in billing)
check('server validation precedes Play settlement helpers', evm.find('repo.validateCoinPurchase') < evm.find('consumeAfterServerVerification') and evm.find('repo.verifyVip') < evm.find('acknowledgeAfterServerVerification'))
print('[PASS] VC-ANDROID-PH08-R02 compile-risk regression: 19/19 PASS')
