from pathlib import Path
import json, re
ROOT=Path(__file__).resolve().parents[1]
def text(p): return (ROOT/p).read_text(encoding='utf-8')
def check(name, cond):
    if not cond: raise SystemExit(f'[FAIL] {name}')
    print(f'[PASS] {name}')
settings=text('settings.gradle.kts'); app=text('app/build.gradle.kts'); props=text('gradle.properties'); nav=text('app/src/main/java/app/voicecloud/android/navigation/VoiceCloudNavHost.kt')
api=text('feature/settings/src/main/java/app/voicecloud/feature/settings/data/SettingsApi.kt')
repo=text('feature/settings/src/main/java/app/voicecloud/feature/settings/data/SettingsRepository.kt')
models=text('feature/settings/src/main/java/app/voicecloud/feature/settings/model/SettingsModels.kt')
vm=text('feature/settings/src/main/java/app/voicecloud/feature/settings/ui/SettingsViewModel.kt')
ui=text('feature/settings/src/main/java/app/voicecloud/feature/settings/ui/SettingsScreens.kt')
root=text('app/src/main/java/app/voicecloud/android/ui/VoiceCloudRoot.kt')
auth_repo=text('feature/auth/src/main/java/app/voicecloud/feature/auth/data/AuthRepository.kt')
auth_vm=text('feature/auth/src/main/java/app/voicecloud/feature/auth/ui/AuthViewModel.kt')
discovery=text('feature/discovery/src/main/java/app/voicecloud/feature/discovery/ui/DiscoveryScreens.kt')
live=text('feature/live/src/main/java/app/voicecloud/feature/live/ui/LiveRoomScreens.kt')
contract=json.loads(text('contracts/api/VC-ANDROID-R06-API-CONTRACT-R01.json'))
ops={(x.get('method'),x.get('path')) for x in contract.get('operations',[])}
check('PH09 settings module registered', 'include(":feature:settings")' in settings)
check('PH09 settings module consumed by app', 'implementation(project(":feature:settings"))' in app)
check('PH09 app version declared', 'versionName = "1.0.0-ph09"' in app)
required=[('GET','/users/settings'),('PATCH','/users/settings'),('GET','/users/privacy'),('PATCH','/users/privacy'),('GET','/auth/sessions'),('GET','/auth/sessions/:param'),('DELETE','/auth/sessions/:param'),('GET','/auth/devices'),('GET','/auth/devices/:param'),('DELETE','/auth/devices/:param'),('GET','/auth/history'),('POST','/auth/logout-all'),('GET','/cms/pages'),('GET','/cms/pages/:param'),('GET','/config/maintenance'),('POST','/contact'),('POST','/reports'),('GET','/reports/my-reports'),('GET','/reports/targets/search'),('GET','/reports/targets/:param/:param')]
for method,path in required: check(f'R06 contract contains {method} {path}', (method,path) in ops)
check('settings API wires canonical preference endpoints', all(x in api for x in ['@GET("users/settings")','@PATCH("users/settings")','@GET("users/privacy")','@PATCH("users/privacy")']))
check('security API wires sessions devices history and revoke', all(x in api for x in ['@GET("auth/sessions")','@DELETE("auth/sessions/{sessionId}")','@GET("auth/devices")','@DELETE("auth/devices/{deviceId}")','@GET("auth/history")']))
check('CMS support and maintenance endpoints wired', all(x in api for x in ['@GET("cms/pages")','@GET("cms/pages/{slug}")','@POST("contact")','@GET("config/maintenance")']))
check('reporting uses canonical consumer endpoints', all(x in api for x in ['@POST("reports")','@GET("reports/my-reports")','@GET("reports/targets/search")','@GET("reports/targets/{targetType}/{targetId}")']))
check('notifications persist through user-settings authority', 'notificationPreferences' in repo and 'api.updateSettings' in repo and 'return preferences()' in repo)
check('privacy uses exact supported permission authority', all(x in repo for x in ['messagingPermission','followPermission','invitationPermission','visitorPermission','allowVisitorTracking','anonymousVisiting']) and 'api.updatePrivacy' in repo)
check('voice preferences use supported backend settings', all(x in repo for x in ['audioPreset','noiseSuppression','echoCancellation','agc']) and 'updateVoice' in repo)
check('appearance supports Light Dark System', all(x in root for x in ['ThemePreference.LIGHT','ThemePreference.DARK','ThemePreference.SYSTEM','isSystemInDarkTheme()']) and 'preferences.setTheme' in repo)
check('application language is English-only', 'language = raw.string("language").ifBlank { "en" }' in repo and 'mapOf("theme" to backendValue, "language" to "en")' in repo and 'English' in ui)
check('safe session and device models exclude credential fields', all(secret.lower() not in models.lower() for secret in ['sessionToken','refreshTokenHash','pushToken','userId']))
check('login history is bounded to 100 entries', 'api.history(100)' in repo and '.take(100)' in repo)
check('session and device revoke remain backend-authoritative', 'api.revokeSession(id)' in repo and 'api.revokeDevice(id)' in repo)
check('logout-all clears local session only after backend success', re.search(r'if \(allDevices\).*?authenticatedApi\.logoutAll\(\).*?if \(!response\.isSuccessful\) throw.*?clearLocalSession\(\)', auth_repo, re.S) is not None)
check('settings failures drive global session and maintenance handling', 'SettingsEvent.SessionExpired' in vm and 'SettingsEvent.Maintenance' in vm and 'handleAuthenticatedFailure(401)' in nav and 'handleAuthenticatedFailure(503' in nav)
check('restricted account routing is enforced after authentication', 'isRestrictedAccount' in auth_repo and 'repository.isRestrictedAccount(user)' in auth_vm)
check('Help FAQ legal uses Admin CMS', 'HelpCenterScreen' in ui and 'CmsContentScreen' in ui and 'loadCmsPages' in vm and 'loadCmsPage' in vm)
check('Contact Support uses persisted backend submission', 'ContactSupportScreen' in ui and 'repository.contact' in vm and 'ContactSupportRequest' in models)
check('reporting supports only normal User and Room targets in Android', 'enum class ReportTargetType { USER, ROOM }' in models and 'ReportReason' in models)
check('reporting reasons match backend enum', all(x in models for x in ['SPAM','ABUSE','HARASSMENT','FAKE_PROFILE','SEXUAL_CONTENT','VIOLENCE','OTHER']))
check('human-readable report target selection is present', 'searchReportTargets' in repo and 'reportTargets' in vm and 'Search people' in ui and 'Search rooms' in ui)
check('public profile exposes contextual report', 'onReport' in discovery and 'Report profile' in discovery and 'ReportTargetType.USER' in nav)
check('live room exposes contextual report', 'onReport' in live and 'Text("Report",' in live and 'ReportTargetType.ROOM' in nav)
check('Safety Center links report blocked privacy and community', 'SafetyCenterScreen' in ui and all(x in nav for x in ['VoiceCloudRoutes.Report','VoiceCloudRoutes.BlockedUsers','VoiceCloudRoutes.PrivacySettings','VoiceCloudRoutes.Communities']))
check('My Profile exposes Settings Security and Safety Center', all(x in discovery for x in ['onSettings','onSecurity','onSafety','Settings','Security & devices','Safety Center']))
check('PH09 does not manufacture password or 2FA mutations', not re.search(r'@(?:POST|PATCH|PUT)\("[^"]*(password|two-factor|2fa)', api, re.I))
check('PH09 does not manufacture trusted-device semantics', 'trusted device' not in (ui+models+repo).lower())
check('PH09 does not invent evidence upload or live-chat support', 'rememberLauncherForActivityResult' not in ui and 'ActivityResultContracts.GetContent' not in ui and 'The app does not promise live chat or fixed response times.' in ui)
check('PH09 presentation has no component hard-coded hex colours', re.search(r'Color\(0x[0-9A-Fa-f]+\)|#[0-9A-Fa-f]{6,8}', ui+root) is None)

check('Gradle 9.5 tooling parallelism is explicitly declared', 'org.gradle.tooling.parallel=true' in props)
check('PH09-R08 Gradle authority contract is present', (ROOT/'contracts/VC-ANDROID-PH09-R08-GRADLE-PROPERTIES-AUTHORITY.json').exists())

check('PH09-R08 device instrumentation derives app identity from AGP metadata', 'output-metadata.json' in text('scripts/VC-ANDROID-DEVICE-INSTRUMENTATION.ps1'))
check('PH09-R08 device instrumentation is explicit-user aware', 'get-current-user' in text('scripts/VC-ANDROID-DEVICE-INSTRUMENTATION.ps1') and "'--user', [string]$currentUser" in text('scripts/VC-ANDROID-DEVICE-INSTRUMENTATION.ps1'))
check('PH09-R08 warning closure gate is present', (ROOT/'scripts/ph09_r08_warning_closure_regression.py').exists())

check('PH09-R08 real PowerShell parser gate is present', (ROOT/'scripts/VC-ANDROID-POWERSHELL-PARSER-CHECK.ps1').exists())
check('PH09-R08 PowerShell surface regression is present', (ROOT/'scripts/ph09_r08_powershell_surface_regression.py').exists())
print('[PASS] VC-ANDROID-PH09-R08 source authority complete')
