from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
def t(p): return (ROOT/p).read_text(encoding='utf-8')
def check(name, cond):
    if not cond: raise SystemExit(f'[FAIL] {name}')
    print(f'[PASS] {name}')
models=t('feature/settings/src/main/java/app/voicecloud/feature/settings/model/SettingsModels.kt')
repo=t('feature/settings/src/main/java/app/voicecloud/feature/settings/data/SettingsRepository.kt')
api=t('feature/settings/src/main/java/app/voicecloud/feature/settings/data/SettingsApi.kt')
vm=t('feature/settings/src/main/java/app/voicecloud/feature/settings/ui/SettingsViewModel.kt')
ui=t('feature/settings/src/main/java/app/voicecloud/feature/settings/ui/SettingsScreens.kt')
auth=t('feature/auth/src/main/java/app/voicecloud/feature/auth/data/AuthRepository.kt')
check('safe session model contains no server credential fields', not re.search(r'(sessionToken|refreshTokenHash|userId)', models, re.I))
check('safe device model contains no push token or owner id', not re.search(r'(pushToken|userId)', models, re.I))
check('security parser projects only explicit safe fields', 'sessionFrom(' in repo and 'deviceFrom(' in repo and 'SafeSession(' in repo and 'SafeDevice(' in repo)
check('current session/device are derived without exposing owner credentials', 'preferences.sessionId.first()' in repo and 'preferences.deviceId.first()' in repo)
check('login history capped at backend maximum 100', '@GET("auth/history")' in api and 'limit: Int = 100' in api and '.take(100)' in repo)
check('revoke actions call canonical server DELETEs', '@DELETE("auth/sessions/{sessionId}")' in api and '@DELETE("auth/devices/{deviceId}")' in api)
check('sign out all requires successful server response before local clear', auth.find('if (!response.isSuccessful) throw') < auth.find('clearLocalSession()', auth.find('if (allDevices)')))
check('normal sign out remains locally recoverable offline', 'runCatching { authenticatedApi.logout() }' in auth and 'clearLocalSession()' in auth)
check('privacy enum choices match backend validators', all(x in ui for x in ['"following"','"approval"','"friends"','"none"']))
check('report request transmits canonical type id reason description only', all(x in models for x in ['val targetType: String','val targetId: String','val reason: String','val description: String?']) and 'evidence' not in models.lower())
check('report reasons match canonical backend enum', 'enum class ReportReason { SPAM, ABUSE, HARASSMENT, FAKE_PROFILE, SEXUAL_CONTENT, VIOLENCE, OTHER }' in models)
check('report target IDs remain internal to selected target', 'targetId = target.id' in repo and 'target.id' not in ui)
check('raw database diagnostics are sanitized', all(x in vm.lower() for x in ['relation ','postgres','typeorm','constraint','stack trace']))
check('401 and 503 propagate to global auth state', 'SettingsEvent.SessionExpired' in vm and 'SettingsEvent.Maintenance' in vm)
check('no unsupported 2FA/change-password/trusted-device mutation exists', not re.search(r'(change password|two-factor|2fa|trusted device)', (api+repo+vm).lower()))
print('[PASS] VC-ANDROID-PH09-R08 security/privacy authority regression: 15/15 PASS')
