from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def r(rel): return (ROOT/rel).read_text(encoding='utf-8')
def ck(name, ok): checks.append(ok); print(('[PASS] ' if ok else '[FAIL] ')+name)
build=r('feature/creator/build.gradle.kts'); api=r('feature/creator/src/main/java/app/voicecloud/feature/creator/data/CreatorApi.kt'); repo=r('feature/creator/src/main/java/app/voicecloud/feature/creator/data/CreatorRepository.kt'); vm=r('feature/creator/src/main/java/app/voicecloud/feature/creator/ui/CreatorViewModel.kt'); screens=r('feature/creator/src/main/java/app/voicecloud/feature/creator/ui/CreatorScreens.kt'); nav=r('app/src/main/java/app/voicecloud/android/navigation/VoiceCloudNavHost.kt'); auth_repo=r('feature/auth/src/main/java/app/voicecloud/feature/auth/data/AuthRepository.kt'); auth_vm=r('feature/auth/src/main/java/app/voicecloud/feature/auth/ui/AuthViewModel.kt')
ck('Creator module declares Compose', 'buildFeatures { compose = true }' in build)
ck('Creator module declares Hilt compiler', 'ksp(libs.hilt.compiler)' in build)
ck('Creator module declares Retrofit/Moshi', 'libs.retrofit.core' in build and 'libs.moshi.kotlin' in build)
ck('Retrofit wildcard body maps are suppressed', '@JvmSuppressWildcards Any?' in api)
ck('Creator Any response parser avoids unsafe casts', 'as? Map<*, *>' in repo and 'as? List<*>' in repo)
ck('Creator generic empty maps are explicit', 'emptyMap<Any?, Any?>()' in repo)
ck('Creator dashboard metric extraction uses firstNotNullOfOrNull safely', 'firstNotNullOfOrNull' in repo)
ck('Creator load cancellation is generation-safe', 'loadGeneration' in vm and 'generation == loadGeneration' in vm)
ck('Creator state uses StateFlow', 'StateFlow<CreatorUiState>' in vm and '.asStateFlow()' in vm)
ck('Creator auth events use buffered Channel', 'Channel<CreatorEvent>(Channel.BUFFERED)' in vm)
ck('Creator HttpException status checks are exhaustive for portal states', 'setOf(401, 403, 503)' in vm)
ck('Creator screens import rememberSaveable from saveable package', 'import androidx.compose.runtime.saveable.rememberSaveable' in screens)
ck('Creator screens import Compose Modifier', 'import androidx.compose.ui.Modifier' in screens)
ck('Creator screens use Material3 NavigationBar', 'NavigationBar {' in screens and 'NavigationBarItem(' in screens)
ck('Creator screens do not depend on experimental FlowRow', 'FlowRow' not in screens)
ck('Creator CMS uses Android Html safely', 'Html.fromHtml' in screens and 'Html.FROM_HTML_MODE_LEGACY' in screens)
ck('Creator contact fields declare email/phone keyboard types', 'KeyboardType.Email' in screens and 'KeyboardType.Phone' in screens)
ck('Creator dynamic CMS route is URI encoded and decoded', 'Uri.encode(slug.trim())' in nav and 'Uri.decode(entry.arguments?.getString("slug").orEmpty())' in nav)
ck('Creator CMS page state is cleared on route dispose', 'DisposableEffect(slug)' in nav and 'creatorViewModel.clearCmsPage()' in nav)
ck('Auth portal switching imports LastPortal', 'LastPortal.CREATOR' in auth_vm and 'LastPortal.USER' in auth_vm)
ck('cross-portal switch clears previous navigation stack', 'routeUser(user, clear = true)' in auth_vm and 'private suspend fun routeUser(user: AuthUser, clear: Boolean = false)' in auth_vm)
ck('Auth repository portal switch refreshes /auth/me identity', 'val user = requireBody(authenticatedApi.me())' in auth_repo[auth_repo.index('suspend fun switchPortal'):])
ck('Auth portal switch rejects Admin and Super Admin', 'VoiceCloudRole.ADMIN, VoiceCloudRole.SUPER_ADMIN' in auth_repo[auth_repo.index('suspend fun switchPortal'):])
ck('PH10 route callbacks use method references with matching arity', all(x in nav for x in ['onSave = creatorViewModel::saveProfile','onSave = creatorViewModel::saveSettings','onSubmit = creatorViewModel::contact']))
ck('No obvious Kotlin conflict markers', not any(x in '\n'.join([api,repo,vm,screens,nav,auth_repo,auth_vm]) for x in ['<<<<<<<','>>>>>>>','=======' ]))
ck('No commented-out PH10 imports', not re.search(r'^\s*//\s*import\s+', '\n'.join([api,repo,vm,screens]), re.M))
passed=sum(checks)
if passed != len(checks): raise SystemExit(f'[FAIL] VC-ANDROID-PH10-R01 compile-risk regression: {passed}/{len(checks)} PASS')
print(f'[PASS] VC-ANDROID-PH10-R01 compile-risk regression: {passed}/{len(checks)} PASS')
