from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
checks=[]
def read(rel): return (ROOT/rel).read_text(encoding='utf-8')
def ck(name, ok): checks.append(ok); print(('[PASS] ' if ok else '[FAIL] ')+name)
nav=read('app/src/main/java/app/voicecloud/android/navigation/VoiceCloudNavHost.kt')
auth_repo=read('feature/auth/src/main/java/app/voicecloud/feature/auth/data/AuthRepository.kt')
auth_vm=read('feature/auth/src/main/java/app/voicecloud/feature/auth/ui/AuthViewModel.kt')
api=read('feature/creator/src/main/java/app/voicecloud/feature/creator/data/CreatorApi.kt')
repo=read('feature/creator/src/main/java/app/voicecloud/feature/creator/data/CreatorRepository.kt')
vm=read('feature/creator/src/main/java/app/voicecloud/feature/creator/ui/CreatorViewModel.kt')
screens=read('feature/creator/src/main/java/app/voicecloud/feature/creator/ui/CreatorScreens.kt')
models=read('feature/creator/src/main/java/app/voicecloud/feature/creator/model/CreatorModels.kt')
discovery=read('feature/discovery/src/main/java/app/voicecloud/feature/discovery/ui/DiscoveryScreens.kt')

ck('Creator routes are namespaced under creator/', all(x in nav for x in ['"creator/dashboard"','"creator/profile"','"creator/settings"','"creator/help"','"creator/content/{slug}"','"creator/support/contact"']))
ck('Creator dashboard route is CREATOR-role guarded', 'composable(VoiceCloudRoutes.CreatorDashboard)' in nav and 'normalizedRole != VoiceCloudRole.CREATOR' in nav)
ck('all six PH10 Creator routes carry explicit role guard', nav.count('normalizedRole != VoiceCloudRole.CREATOR') >= 6)
ck('non-Creator switch is rejected by backend identity role', 'throw CreatorRoleRequiredException()' in auth_repo)
ck('Creator switch does not issue login or new token', 'preferences.setLastPortal(target)' in auth_repo and 'storeAuth(' not in auth_repo[auth_repo.index('suspend fun switchPortal(target: LastPortal)'):auth_repo.index('/** FCM registration foundation')])
ck('Creator to VoiceCloud switch reuses existing authenticated identity', 'repository.switchPortal(LastPortal.USER)' in auth_vm)
ck('cross-portal switch clears the previous portal navigation stack', 'routeUser(user, clear = true)' in auth_vm and 'navigate(AuthScreen.CREATOR_READY, true)' in auth_vm)
ck('VoiceCloud to Creator switch is exposed only when role is CREATOR', 'canSwitchToCreator = authState.user?.normalizedRole == VoiceCloudRole.CREATOR' in nav)
ck('Creator access application remains available before Creator authorization', 'VoiceCloudRoutes.CreatorAccess' in nav and 'onApply = { open(VoiceCloudRoutes.CreatorAccess) }' in nav)
ck('Creator dashboard is canonical GET only', '@GET("creator/dashboard")' in api and '@POST("creator/dashboard")' not in api)
ck('Creator profile uses canonical shared user profile authority', '@GET("users/profile/me")' in api and '@PATCH("users/profile")' in api)
ck('Creator settings use canonical shared user settings authority', '@GET("users/settings")' in api and '@PATCH("users/settings")' in api)
ck('Creator help uses Creator-audience CMS', '@GET("cms/creator/pages")' in api and '@GET("cms/creator/pages/{slug}")' in api)
ck('Creator support persists to Admin inbox through /contact', '@POST("contact")' in api)
ck('Creator maintenance uses backend public config authority', '@GET("config/maintenance")' in api and 'repository.maintenance()' in vm)
ck('401/403/503 are global auth-state events', 'error.code() in setOf(401, 403, 503)' in vm and 'handleAuthenticatedFailure(event.httpStatus' in nav)
ck('403 global handling routes Restricted', '403 -> {' in auth_vm and 'navigate(AuthScreen.RESTRICTED' in auth_vm)
ck('401 global handling clears local session', 'repository.invalidateLocalSession()' in auth_vm)
ck('Creator errors sanitize backend database diagnostics', all(x in vm for x in ['"sql"','"postgres"','"typeorm"','"constraint"']))
ck('technical IDs are not rendered as Creator profile UI labels', 'Text(profile.id' not in screens and 'User ID' not in screens)
ck('Creator shell contains only locked PH10 core sections', 'DASHBOARD, PROFILE, SETTINGS, HELP' in models)
ck('Creator source contains no Admin endpoints', 'admin/' not in '\n'.join([api,repo,vm,screens]))
ck('Creator source contains no PH11 live/schedule endpoints', not any(x in api for x in ['rooms/','scheduled-rooms','rtc/rooms']))
ck('Creator source contains no PH12 messaging/subscriber mutation endpoints', not any(x in api for x in ['messages','creator/plans','creator/subscribers']))
ck('Creator source contains no PH13 wallet/payout/verification endpoints', not any(x in api for x in ['wallet/','payout','hosts/verification','stream-credentials']))
ck('Creator help has no mail-client intent fallback', 'ACTION_SENDTO' not in screens and 'Intent(' not in screens)
ck('Creator profile update cannot edit role/email/username', all(f'"{x}" to' not in repo[repo.index('suspend fun updateProfile'):repo.index('suspend fun settings') ] for x in ['role','email','username']))
ck('Creator settings language remains English-only', '"language" to "en"' in repo)
ck('Creator dashboard does not fabricate fallback metric values', 'displayValue(entry.second).takeIf(String::isNotBlank)' in repo and '?: "0"' not in repo)
ck('Creator support does not promise live chat or response SLA', 'promise a response time' in screens and 'live chat' not in screens.lower())
ck('Creator centralized theme is used for all Creator page shells', screens.count('VoiceCloudTheme(portal = PortalTheme.Creator') >= 3)

passed=sum(checks)
if passed != len(checks): raise SystemExit(f'[FAIL] VC-ANDROID-PH10-R01 portal authority regression: {passed}/{len(checks)} PASS')
print(f'[PASS] VC-ANDROID-PH10-R01 portal authority regression: {passed}/{len(checks)} PASS')
