from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def read(rel): return (ROOT/rel).read_text(encoding='utf-8')
def ck(name,ok): checks.append(bool(ok)); print(('[PASS] ' if ok else '[FAIL] ')+name)
nav=read('app/src/main/java/app/voicecloud/android/navigation/VoiceCloudNavHost.kt')
api=read('feature/creator/src/main/java/app/voicecloud/feature/creator/data/CreatorApi.kt')
repo=read('feature/creator/src/main/java/app/voicecloud/feature/creator/data/CreatorRepository.kt')
vm=read('feature/creator/src/main/java/app/voicecloud/feature/creator/ui/CreatorViewModel.kt')
screens=read('feature/creator/src/main/java/app/voicecloud/feature/creator/ui/CreatorScreens.kt')
engrepo=read('feature/engagement/src/main/java/app/voicecloud/feature/engagement/data/EngagementRepository.kt')
engvm=read('feature/engagement/src/main/java/app/voicecloud/feature/engagement/ui/EngagementViewModel.kt')
disc=read('feature/discovery/src/main/java/app/voicecloud/feature/discovery/data/DiscoveryRepository.kt')
ck('PH12 app version declared','versionName = "1.0.0-ph12"' in read('app/build.gradle.kts'))
for route in ['CreatorAudience','CreatorFollowers','CreatorSubscribers','CreatorPlans','CreatorMessages','CreatorConversation']: ck('PH12 route '+route,f'const val {route}' in nav)
for fn in ['CreatorAudienceScreen','CreatorFollowersScreen','CreatorSubscribersScreen','CreatorPlansScreen']: ck('PH12 screen '+fn,f'fun {fn}(' in screens)
ck('Creator module reuses discovery social authority','implementation(project(":feature:discovery"))' in read('feature/creator/build.gradle.kts'))
ck('followers page through backend authority','allFollowers(' in disc and 'allFollowing(' in disc and 'totalPages' in disc)
ck('follow-back reconciles backend result','setFollowing(userId, follow)' in vm and 'result.isFollowing' in vm)
ck('Creator direct inbox requests direct type','type = "direct"' in engrepo and 'filter { it.type.equals("direct"' in engrepo)
ck('Creator direct detail fails closed for non-direct','Only direct creator conversations are available here.' in engrepo)
ck('Creator messages have dedicated ViewModel entry','loadCreatorDirectConversations' in engvm and 'loadCreatorDirectConversation' in engvm)
ck('Plan CRUD and archive are implemented',all(x in api for x in ['@GET("creator/plans")','@POST("creator/plans")','@PATCH("creator/plans/{id}")','@DELETE("creator/plans/{id}")']))
ck('Subscriber directory endpoint is implemented','@GET("creator/subscribers")' in api)
ck('No paid subscription acquisition endpoint fabricated','@POST("creator/subscribe/' not in api and 'my-subscriptions' not in api)
ck('PH13 creator financial routes are not pulled forward',all(x not in nav for x in ['CreatorWallet','CreatorEarnings','CreatorPayout','CreatorAnalytics']))
ck('Creator role guards cover PH12 graph',nav.count('authState.user?.normalizedRole != VoiceCloudRole.CREATOR') >= 18)
passed=sum(checks)
if passed!=len(checks): raise SystemExit(f'[FAIL] VC-ANDROID-PH12-R01 source authority: {passed}/{len(checks)} PASS')
print(f'[PASS] VC-ANDROID-PH12-R01 source authority: {passed}/{len(checks)} PASS')
