from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
acc = (ROOT/'scripts/VC-ANDROID-PH13-R12-ACCEPTANCE.cmd').read_text(encoding='utf-8')
diag = (ROOT/'scripts/VC-ANDROID-PH13-R12-SOURCE-DIAGNOSTIC.ps1').read_text(encoding='utf-8')
preserve = (ROOT/'scripts/ph13_r12_product_preservation_regression.py').read_text(encoding='utf-8')
integrity = (ROOT/'scripts/ph13_r12_delivery_integrity.py').read_text(encoding='utf-8')
sim = (ROOT/'scripts/ph13_r12_workstation_artifact_regression.py').read_text(encoding='utf-8')
checks=[]
def ck(label, cond):
    checks.append(bool(cond)); print(('[PASS] ' if cond else '[FAIL] ') + label)
ck('R12 source diagnostic wired','VC-ANDROID-PH13-R12-SOURCE-DIAGNOSTIC.ps1' in acc)
ck('R12 delivery integrity wired','ph13_r12_delivery_integrity.py' in acc)
ck('R12 preservation regression wired','ph13_r12_product_preservation_regression.py' in diag)
ck('R12 workstation-artifact simulation wired','ph13_r12_workstation_artifact_regression.py' in diag)
ck('R11 resilient device closure retained','VC-ANDROID-PH13-R11-DEVICE-CLOSURE.ps1' in acc)
ck('R12 does not repeat full compile/test/lint/assembly chain', all(x not in acc for x in ['compileDebugKotlin','compileStagingKotlin','compileReleaseKotlin','lintDebug','assembleRelease']))
ck('R12 enables delayed expansion','setlocal EnableExtensions EnableDelayedExpansion' in acc)
ck('R12 captures device exit code with delayed expansion','set "VC_DEVICE_RC=!ERRORLEVEL!"' in acc)
ck('R12 branches on delayed device result','if "!VC_DEVICE_RC!"=="2"' in acc and 'if not "!VC_DEVICE_RC!"=="0"' in acc)
ck('R12 has no stale percent-expanded device rc inside block','%VC_DEVICE_RC%' not in acc)
ck('no-device remains pending/nonfatal','VC_DEVICE_PENDING=1' in acc and '[DEVICE-PENDING]' in acc)
ck('genuine device failure remains fail-closed','set /a VC_FAILURE_GROUPS+=1' in acc and 'genuine device/instrumentation failure' in acc)
ck('preservation ignores generated dirs consistently', "'.gradle'" in preserve and "'build'" in preserve and 'is_generated' in preserve)
ck('preservation ignores generated files consistently', "'local.properties'" in preserve and "'gradle-daemon-jvm.properties'" in preserve)
ck('integrity has same workstation-generated directory authority', 'IGNORED_GENERATED_DIRS' in integrity and "'.gradle'" in integrity)
ck('integrity has same workstation-generated file authority', 'IGNORED_GENERATED_FILES' in integrity and "'local.properties'" in integrity)
ck('simulation contains exact R11 reported local.properties','local.properties' in sim)
ck('simulation contains exact R11 reported gradle daemon JVM file','gradle/gradle-daemon-jvm.properties' in sim)
ck('simulation contains exact R11 reported .gradle cache paths','.gradle/9.5.0/fileHashes/fileHashes.bin' in sim and '.gradle/buildOutputCleanup/cache.properties' in sim)
ck('simulation verifies unknown drift still fails closed','unexpected-product-drift.txt' in sim and 'returncode == 0' in sim)
ck('R12 final acceptance can succeed with device pending','exit /b 0' in acc and '[PENDING] Physical-device instrumentation remains pending' in acc)
if not all(checks): raise SystemExit(1)
print(f'[PASS] VC-ANDROID-PH13-R12 acceptance wiring: {len(checks)}/{len(checks)} PASS')
