from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
dev=(ROOT/'scripts/VC-ANDROID-DEVICE-INSTRUMENTATION.ps1').read_text(encoding='utf-8')
closure=(ROOT/'scripts/VC-ANDROID-PH13-R11-DEVICE-CLOSURE.ps1').read_text(encoding='utf-8')
acc=(ROOT/'scripts/VC-ANDROID-PH13-R11-ACCEPTANCE.cmd').read_text(encoding='utf-8')
checks=[]
def ck(label,cond): checks.append(bool(cond)); print(('[PASS] ' if cond else '[FAIL] ')+label)
ck('device script exposes PreflightOnly switch','[switch]$PreflightOnly' in dev)
ck('device preflight exits after healthy device/user selection and before APK metadata',dev.index("if ($PreflightOnly)") < dev.index("$appMetadataPath ="))
ck('no healthy device remains distinct exit code 2',"No healthy authorized Android device" in dev and 'exit 2' in dev)
ck('R11 product manifest is verified before device work','Test-ProductManifest -Root $sourceRoot' in closure)
ck('R11 performs device preflight before prior-artifact search',closure.index('[DEVICE PREFLIGHT]') < closure.index('$reuse = Find-VerifiedPriorWorkspace'))
ck('R11 no-device preflight skips build entirely','Skipping artifact preparation/build entirely' in closure and 'exit 2' in closure)
ck('R11 searches R10 and R09 prior build workspaces','VoiceCloud-PH13-R10-DEVICE-*' in closure and 'VoiceCloud-PH13-R09-*' in closure)
ck('R11 reuses only hash-verified prior artifacts','Test-ProductManifest -Root $dir.FullName' in closure and '[FAST PATH]' in closure)
ck('R11 second device preflight occurs before fallback Gradle build','second device preflight' in closure.lower() and closure.index('second device preflight') < closure.index('[BOOTSTRAP]'))
ck('fallback remains limited to Debug and androidTest prerequisites',"':app:assembleDebug' ':app:assembleDebugAndroidTest'" in closure)
ck('direct APK install remains non-incremental','--no-incremental' in dev)
ck('direct install timeout remains bounded at 180 seconds','-TimeoutSeconds 180' in dev)
ck('install fallback and exact installed APK hash verification retained','Test-InstalledApkMatches' in dev and "'push'" in dev and "'pm', 'install'" in dev)
ck('instrumentation bounded recovery retained','Instrumentation client timed out once' in dev and '-TimeoutSeconds 300' in dev)
ck('USB transport remains preferred over wireless adb','Sort-Object Rank, Serial' in dev)
ck('acceptance treats no-device exit 2 as pending, not failure','VC_DEVICE_PENDING=1' in acc and 'set /a VC_FAILURE_GROUPS+=1' not in acc[acc.index('if "%VC_DEVICE_RC%"=="2"'):acc.index(') else if not "%VC_DEVICE_RC%"=="0"')])
ck('acceptance still fails on genuine device error','R11 physical-device closure encountered a real device/instrumentation failure' in acc and 'set /a VC_FAILURE_GROUPS+=1' in acc)
ck('pending-device host acceptance exits success','[PENDING] Physical-device instrumentation remains pending' in acc and 'exit /b 0' in acc)
if not all(checks): raise SystemExit(1)
print(f'[PASS] VC-ANDROID-PH13-R11 device closure regression: {len(checks)}/{len(checks)} PASS')
