from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; checks=[]
def r(p): return (ROOT/p).read_text(encoding='utf-8')
def ck(n,o): checks.append(bool(o)); print(('[PASS] ' if o else '[FAIL] ')+n)
api=r('feature/creator/src/main/java/app/voicecloud/feature/creator/data/CreatorApi.kt'); repo=r('feature/creator/src/main/java/app/voicecloud/feature/creator/data/CreatorRepository.kt')
hapi=r('feature/hosting/src/main/java/app/voicecloud/feature/hosting/data/HostingApi.kt'); hrepo=r('feature/hosting/src/main/java/app/voicecloud/feature/hosting/data/HostingRepository.kt')
for verb,path in [('GET','analytics'),('GET','wallet/balance'),('GET','wallet/summary'),('GET','wallet/transactions'),('GET','gifts/history'),('GET','creator/earnings'),('POST','creator/payout-request'),('GET','creator/payout-requests'),('GET','creator/payout-requests/{id}')]:
    ck(f'{verb} {path} wired',f'@{verb}("{path}")' in api)
ck('CreatePayoutRequest diamondAmount exact','"diamondAmount" to diamondAmount' in repo)
ck('CreatePayoutRequest payoutMethod exact','"payoutMethod" to method' in repo)
ck('CreatePayoutRequest operationKey exact','"operationKey" to "android-payout-${UUID.randomUUID()}"' in repo)
ck('No invented payout accountDetails payload','"accountDetails" to' not in repo)
ck('Payout minimum 100','diamondAmount >= 100' in repo)
ck('Payout method allowlist authoritative', 'setOf("BANK_TRANSFER", "PAYPAL", "STRIPE", "CRYPTO")' in repo)
for verb,path in [('POST','hosts/apply'),('GET','hosts/progression'),('GET','hosts/verification/assets'),('POST','hosts/verification/government-id'),('POST','hosts/verification/profile-photo'),('POST','hosts/verification/documents'),('PUT','hosts/verification/assets/{assetId}/replacement')]:
    ck(f'{verb} {path} wired',f'@{verb}("{path}")' in hapi)
ck('ApplyHost DTO realName exact','"realName" to cleanName' in hrepo)
ck('ApplyHost DTO private government asset exact','"governmentIdAssetId" to governmentId' in hrepo)
ck('ApplyHost DTO private selfie asset exact','"selfieAssetId" to selfieId' in hrepo)
ck('ApplyHost DTO supporting assets exact','"supportingDocumentAssetIds" to supporting' in hrepo)
ck('ApplyHost does not use deprecated public URL DTO fields','"documentUrl" to' not in hrepo and '"selfieUrl" to' not in hrepo)
ck('Verification uploads use multipart','@Multipart @POST("hosts/verification/government-id")' in hapi and '@Part file: MultipartBody.Part' in hapi)
ck('Replacement sends only replacementAssetId','mapOf("replacementAssetId" to replacementId)' in hrepo)
ck('Private asset list retained after mutations','return verificationAssets()' in hrepo)
ck('Stream credential GET prohibited','creator/stream-credentials' not in api)
ck('Stream credential regenerate prohibited','stream-credentials/regenerate' not in api)
passed=sum(checks)
if passed!=len(checks): raise SystemExit(f'[FAIL] VC-ANDROID-PH13-R01 backend contract: {passed}/{len(checks)} PASS')
print(f'[PASS] VC-ANDROID-PH13-R01 backend contract: {passed}/{len(checks)} PASS')
