from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
cmd=(ROOT/'scripts/VC-ANDROID-PH13-R15-ACCEPTANCE.cmd').read_text(encoding='utf-8')
ps=(ROOT/'scripts/VC-ANDROID-PH13-R15-ISOLATED-BUILD.ps1').read_text(encoding='utf-8')
diag=(ROOT/'scripts/VC-ANDROID-PH13-R15-SOURCE-DIAGNOSTIC.ps1').read_text(encoding='utf-8')
checks=[]
def ck(n,o): checks.append(bool(o)); print(('[PASS] ' if o else '[FAIL] ')+n)
ck('R15 compiler closure regression wired before Android build','ph13_r15_compiler_closure_regression.py' in diag and cmd.index('SOURCE-DIAGNOSTIC')<cmd.index('ISOLATED-BUILD'))
ck('R15 product preservation wired','ph13_r15_product_preservation_regression.py' in diag)
ck('R14 full physical-device-driven visual regression retained','ph13_r14_visual_device_regression.py' in diag)
ck('R15 full isolated build wired','VC-ANDROID-PH13-R15-ISOLATED-BUILD.ps1' in cmd)
ck('R15 delivery integrity wired','ph13_r15_delivery_integrity.py' in cmd)
ck('delayed ERRORLEVEL capture retained','set "VC_ANDROID_RC=!ERRORLEVEL!"' in cmd)
ck('compileDebugKotlin remains mandatory',':app:compileDebugKotlin' in ps)
ck('compileStagingKotlin remains mandatory',':app:compileStagingKotlin' in ps)
ck('compileReleaseKotlin remains mandatory',':app:compileReleaseKotlin' in ps)
ck('unit tests retained',"@('test')" in ps)
ck('all-variant lint retained',"@('lintDebug','lintStaging','lintRelease')" in ps)
ck('all assemblies/androidTest retained',all(x in ps for x in (':app:assembleDebug',':app:assembleStaging',':app:assembleRelease',':app:assembleDebugAndroidTest')))
ck('physical-device instrumentation retained','VC-ANDROID-DEVICE-INSTRUMENTATION.ps1' in ps)
ck('R15 isolated workspace used','VoiceCloud-PH13-R15-' in ps)
ck('R14 persistent Gradle cache intentionally reused to reduce repeat download/build burden',".voicecloud\\gradle-r14-cache" in ps)
ck('device pending remains distinct', 'exit /b 2' in cmd and 'VC_DEVICE_PENDING' in cmd)
ck('full acceptance only after device success','VC-ANDROID-PH13-R15 FULL ACCEPTANCE' in cmd)
if not all(checks): raise SystemExit(f'[FAIL] VC-ANDROID-PH13-R15 acceptance wiring: {sum(checks)}/{len(checks)} PASS')
print(f'[PASS] VC-ANDROID-PH13-R15 acceptance wiring: {len(checks)}/{len(checks)} PASS')
