package app.voicecloud.core.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class VoiceCloudSemanticColors(
    val primary: Color,
    val primaryContainer: Color,
    val onPrimary: Color,
    val secondary: Color,
    val accent: Color,
    val background: Color,
    val surface: Color,
    val surfaceElevated: Color,
    val surfaceSoft: Color,
    val surfaceDark: Color,
    val liveSurface: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val textOnDark: Color,
    val outline: Color,
    val live: Color,
    val success: Color,
    val warning: Color,
    val error: Color,
    val info: Color,
    val premium: Color,
    val coin: Color,
)

val LocalVoiceCloudColors = staticCompositionLocalOf { consumerLightColors() }

internal fun consumerLightColors() = VoiceCloudSemanticColors(
    primary = ConsumerColors.Violet,
    primaryContainer = ConsumerColors.Lavender,
    onPrimary = Color.White,
    secondary = ConsumerColors.Indigo,
    accent = ConsumerColors.Ice,
    background = ConsumerColors.Cloud,
    surface = ConsumerColors.Surface,
    surfaceElevated = ConsumerColors.Surface,
    surfaceSoft = ConsumerColors.SurfaceSoft,
    surfaceDark = CommonColors.Navy,
    liveSurface = CommonColors.Navy,
    textPrimary = ConsumerColors.Text,
    textSecondary = ConsumerColors.TextMuted,
    textMuted = ConsumerColors.TextMuted,
    textOnDark = Color.White,
    outline = ConsumerColors.Border,
    live = CommonColors.Live,
    success = CommonColors.Success,
    warning = CommonColors.Warning,
    error = CommonColors.Error,
    info = CommonColors.Info,
    premium = CommonColors.Premium,
    coin = CommonColors.Coin,
)

internal fun consumerDarkColors() = VoiceCloudSemanticColors(
    primary = Color(0xFF8B7CFF),
    primaryContainer = Color(0xFF2A2458),
    onPrimary = CommonColors.Navy,
    secondary = Color(0xFF8090FF),
    accent = ConsumerColors.DarkSapphire,
    background = ConsumerColors.DarkBackground,
    surface = ConsumerColors.DarkSurface,
    surfaceElevated = ConsumerColors.DarkSurfaceSoft,
    surfaceSoft = ConsumerColors.DarkSurfaceSoft,
    surfaceDark = CommonColors.Navy,
    liveSurface = CommonColors.NavySoft,
    textPrimary = ConsumerColors.DarkText,
    textSecondary = ConsumerColors.DarkMuted,
    textMuted = ConsumerColors.DarkMuted,
    textOnDark = Color.White,
    outline = ConsumerColors.DarkBorder,
    live = Color(0xFFFF4D6D),
    success = Color(0xFF4ADE80),
    warning = CommonColors.Warning,
    error = Color(0xFFF87171),
    info = CommonColors.Info,
    premium = CommonColors.Premium,
    coin = CommonColors.Coin,
)

internal fun creatorLightColors() = VoiceCloudSemanticColors(
    primary = CreatorColors.Primary,
    primaryContainer = Color(0xFFDCFCE7),
    onPrimary = Color(0xFF07130D),
    secondary = CreatorColors.Secondary,
    accent = CreatorColors.Accent,
    background = CreatorColors.LightBackground,
    surface = CreatorColors.LightSurface,
    surfaceElevated = CreatorColors.Elevated,
    surfaceSoft = Color(0xFFE4F0EA),
    surfaceDark = CreatorColors.Navigation,
    liveSurface = CreatorColors.Navigation,
    textPrimary = CreatorColors.Text,
    textSecondary = CreatorColors.TextMuted,
    textMuted = CreatorColors.TextMuted,
    textOnDark = CreatorColors.DarkText,
    outline = CreatorColors.Border,
    live = CommonColors.Live,
    success = CommonColors.Success,
    warning = CommonColors.Warning,
    error = Color(0xFFDC2626),
    info = CommonColors.Info,
    premium = CommonColors.Premium,
    coin = CommonColors.Coin,
)

internal fun creatorDarkColors() = VoiceCloudSemanticColors(
    primary = CreatorColors.PrimaryLight,
    primaryContainer = Color(0xFF163226),
    onPrimary = Color(0xFF07130D),
    secondary = CreatorColors.SecondaryLight,
    accent = CreatorColors.Accent,
    background = CreatorColors.DarkBackground,
    surface = CreatorColors.DarkSurface,
    surfaceElevated = CreatorColors.DarkElevated,
    surfaceSoft = CreatorColors.DarkElevated,
    surfaceDark = Color(0xFF07110E),
    liveSurface = Color(0xFF0C1A16),
    textPrimary = CreatorColors.DarkText,
    textSecondary = CreatorColors.DarkMuted,
    textMuted = CreatorColors.DarkMuted,
    textOnDark = CreatorColors.DarkText,
    outline = CreatorColors.DarkBorder,
    live = Color(0xFFFF4D6D),
    success = CreatorColors.PrimaryLight,
    warning = CommonColors.Warning,
    error = Color(0xFFEF4444),
    info = CommonColors.Info,
    premium = CommonColors.Premium,
    coin = CommonColors.Coin,
)
